/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchforRouteImport } from './routes/watchfor'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'

const WatchforRoute = WatchforRouteImport.update({
  id: '/watchfor',
  path: '/watchfor',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/chats': typeof ChatsRoute
  '/checkin': typeof CheckinRoute
  '/history': typeof HistoryRoute
  '/summary': typeof SummaryRoute
  '/watchfor': typeof WatchforRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/chats': typeof ChatsRoute
  '/checkin': typeof CheckinRoute
  '/history': typeof HistoryRoute
  '/summary': typeof SummaryRoute
  '/watchfor': typeof WatchforRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/chats': typeof ChatsRoute
  '/checkin': typeof CheckinRoute
  '/history': typeof HistoryRoute
  '/summary': typeof SummaryRoute
  '/watchfor': typeof WatchforRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/chats'
    | '/checkin'
    | '/history'
    | '/summary'
    | '/watchfor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat' | '/chats' | '/checkin' | '/history' | '/summary' | '/watchfor'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/chats'
    | '/checkin'
    | '/history'
    | '/summary'
    | '/watchfor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  ChatsRoute: typeof ChatsRoute
  CheckinRoute: typeof CheckinRoute
  HistoryRoute: typeof HistoryRoute
  SummaryRoute: typeof SummaryRoute
  WatchforRoute: typeof WatchforRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchfor': {
      id: '/watchfor'
      path: '/watchfor'
      fullPath: '/watchfor'
      preLoaderRoute: typeof WatchforRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  ChatsRoute: ChatsRoute,
  CheckinRoute: CheckinRoute,
  HistoryRoute: HistoryRoute,
  SummaryRoute: SummaryRoute,
  WatchforRoute: WatchforRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
